[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://contentforge.netlify.app"
  NEXT_PUBLIC_SUPABASE_URL = "https://jvnavubholyvihvytqkn.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bmF2dWJob2x5dmlodnl0cWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTAxNDEsImV4cCI6MjA2MzE2MDE0MX0.NMNg5xNfPHc6YGCfPXpvJ8_DQWCpqlPR0k8EswFQzsY"
