'use client'

import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { useAuth } from '@/lib/authContext'
import Link from 'next/link'
import { getSupabase } from '@/lib/supabaseClient'
import { useTranslations } from 'next-intl'

function renderMarkdown(text: string) {
  const [mainContent, ctaContent] = text.split('\n\n---CTA---\n')
  const fmt = (s: string) =>
    s.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\*(.+?)\*/g, '<em>$1</em>')
  return (
    <div>
      <div dangerouslySetInnerHTML={{ __html: fmt(mainContent) }} />
      {ctaContent && (
        <>
          <hr className="border-gray-300 my-3" />
          <p className="text-xs text-gray-400 italic" dangerouslySetInnerHTML={{ __html: fmt(ctaContent) }} />
        </>
      )}
    </div>
  )
}

interface Article {
  id: string
  platform: string
  title: string
  content: string
  image_url: string
}

export default function ArticlePage() {
  const router = useRouter()
  const params = useParams()
  const { session } = useAuth()
  const t = useTranslations('articles')
  const productId = params?.id as string

  const [topic, setTopic] = useState('')
  const [selectedPlatforms, setSelectedPlatforms] = useState<string[]>(['facebook'])
  const [imageStyle, setImageStyle] = useState<string>('tech')
  const [includeLink, setIncludeLink] = useState(false)
  const [websiteUrl, setWebsiteUrl] = useState<string>('')
  const [ctaText, setCtaText] = useState<string>('')
  const [loading, setLoading] = useState(false)
  const [articles, setArticles] = useState<Article[]>([])
  const [error, setError] = useState<string | null>(null)
  const [imageUrl, setImageUrl] = useState<string | null>(null)
  const [productLogoUrl, setProductLogoUrl] = useState<string | null>(null)
  const [imageLoading, setImageLoading] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editDraft, setEditDraft] = useState('')
  const [saving, setSaving] = useState(false)

  const platforms = ['facebook', 'linkedin', 'x']

  const imageStyles = [
    { key: 'tech',      name: 'Tech',     desc: 'Moderne og slank teknologiestetikk' },
    { key: 'cinematic', name: 'Cinematic', desc: 'Dramatisk filmestetikk, høy produksjonsverdi' },
    { key: 'warm',      name: 'Varm',     desc: 'Livsstilsfoto, mykt lys, menneskelig stemning' },
    { key: 'surreal',   name: 'Surreal',  desc: 'Surrealistisk konsept, Magritte-inspirert' },
    { key: 'manga',     name: 'Manga',    desc: 'Manga-inspirert, dynamisk og spenstig' },
  ]
  useEffect(() => {
    if (!productId) return
    const supabase = getSupabase()
    supabase
      .from("product_profiles")
      .select("website_url, cta_text, logo_url, article_logo_url")
      .eq("product_id", productId)
      .maybeSingle()
      .then(({ data }: { data: any }) => {
        if (data?.website_url) setWebsiteUrl(data.website_url)
        if (data?.cta_text) {
          setCtaText(data.cta_text)
          // Default off — user chooses explicitly
        }
        // Prefer article_logo_url for article images, fall back to logo_url
        setProductLogoUrl(data?.article_logo_url || data?.logo_url || null)
      })
  }, [productId])


  const togglePlatform = (platform: string) => {
    setSelectedPlatforms((prev) =>
      prev.includes(platform) ? prev.filter((p) => p !== platform) : [...prev, platform]
    )
  }

  const generateArticles = async () => {
    if (!topic.trim()) {
      setError(t('errorTopic'))
      return
    }

    if (selectedPlatforms.length === 0) {
      setError(t('errorPlatform'))
      return
    }

    setLoading(true)
    setError(null)
    setArticles([])

    try {
      const campaignId = `campaign-${Date.now()}`

      // Call API for each platform in parallel
      const promises = selectedPlatforms.map((platform) =>
        fetch('/api/content/produce/article', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            productId,
            campaignId,
            topic,
            platform,
            logoUrl: productLogoUrl,
            imageStyle,
            includeLink,
            websiteUrl,
            ctaText,
          }),
        }).then(async (response) => {
          if (!response.ok) {
            const data = await response.json()
            throw new Error(data.error || `Error generating ${platform} article`)
          }
          return response.json()
        })
      )

      const results = await Promise.all(promises)
      const pending = results.map((result) => result.article).filter(Boolean)
      const ids = pending.map((a: Article) => a.id)

      // Content is now generated by a background function (no CDN timeout on long articles).
      // Poll the article rows until content lands, or give up after ~120s.
      const sb = getSupabase()
      const deadline = Date.now() + 120000
      let generatedArticles: Article[] = []
      while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, 3000))
        const { data } = await sb
          .from('articles')
          .select('id, title, platform, content, image_urls')
          .in('id', ids)
        const rows = (data || []) as any[]
        const ready = rows
          .filter((r) => r.content && String(r.content).trim().length > 0)
          .map((r) => ({ id: r.id, platform: r.platform, title: r.title, content: r.content, image_url: r.image_urls?.[0] || '' }))
        // Done when all are ready, or a row vanished (background marked it failed).
        if (ready.length === ids.length || rows.length < ids.length) { generatedArticles = ready; break }
      }
      if (generatedArticles.length === 0) {
        throw new Error('Genereringen tok for lang tid — prøv igjen om litt.')
      }
      setArticles(generatedArticles)

      // Trigger image generation for each article via the reliable generate-image route
      // Use the first article's topic for the shared image
      if (generatedArticles.length > 0) {
        const firstArticle = generatedArticles[0]
        setImageLoading(true)
        fetch('/api/content/generate-image', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            topic: firstArticle.title || topic,
            productId,
            logoUrl: productLogoUrl,
            articleIds: generatedArticles.map((a: Article) => a.id),
            imageStyle,
          }),
        })
          .then((r) => r.json())
          .then((data) => {
            if (data.imageUrl) {
              setArticles((prev) => prev.map((a) => ({ ...a, image_url: data.imageUrl })))
            }
          })
          .catch((err) => console.error('[article] Image generation failed:', err))
          .finally(() => setImageLoading(false))
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    alert(t('copied'))
  }

  const startEdit = (article: Article) => {
    setEditingId(article.id)
    setEditDraft(article.content)
  }

  const cancelEdit = () => {
    setEditingId(null)
    setEditDraft('')
  }

  const saveEdit = async (articleId: string) => {
    setSaving(true)
    try {
      const supabase = getSupabase()
      const { error } = await supabase
        .from('articles')
        .update({ content: editDraft })
        .eq('id', articleId)
      if (error) throw error
      setArticles((prev) =>
        prev.map((a) => (a.id === articleId ? { ...a, content: editDraft } : a))
      )
      setEditingId(null)
    } catch (err) {
      alert(t('errorSaving', { error: err instanceof Error ? err.message : String(err) }))
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="min-h-screen bg-[var(--paper)]">
      <div className="max-w-6xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <Link href={`/dashboard/products/${productId}`} className="hover:underline mb-4 inline-block">
            {t('backToProduct')}
          </Link>
          <h1 className="text-3xl font-bold text-gray-900">{t('title')}</h1>
          <p className="text-gray-600 mt-2">{t('subtitle')}</p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {/* Form */}
          <div className="md:col-span-1">
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">{t('settingsTitle')}</h2>

              {/* Topic */}
              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">{t('topicLabel')}</label>
                <textarea
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder={t('topicPlaceholder')}
                  rows={4}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--ember-deep)]"
                />
              </div>

              {/* Platforms */}
              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-3">{t('platformsLabel')}</label>
                <div className="space-y-2">
                  {platforms.map((platform) => (
                    <label key={platform} className="flex items-center">
                      <input
                        type="checkbox"
                        checked={selectedPlatforms.includes(platform)}
                        onChange={() => togglePlatform(platform)}
                        className="w-4 h-4 text-[var(--ember-deep)] rounded focus:ring-2 focus:ring-[var(--ember-deep)]"
                      />
                      <span className="ml-2 text-sm text-gray-700 capitalize">{platform}</span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Image Style */}
              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-3">{t('imageStyleLabel')}</label>
                <div className="grid grid-cols-1 gap-2">
                  {imageStyles.map((style) => (
                    <button
                      key={style.key}
                      onClick={() => setImageStyle(style.key)}
                      className={`text-left px-3 py-2 rounded-lg border text-sm transition-colors ${imageStyle === style.key ? "border-[var(--ember-deep)] bg-[var(--ember-tint-bg)] text-[var(--ink)]" : "border-gray-200 hover:border-gray-300 text-gray-700"}`}
                    >
                      <span className="font-medium">{style.name}</span>
                      <span className="text-xs text-gray-500 block">{style.desc}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Product link / CTA */}
              {(websiteUrl || ctaText) && (
                <div className="mb-6">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={includeLink}
                      onChange={(e) => setIncludeLink(e.target.checked)}
                      className="w-4 h-4 text-[var(--ember-deep)] rounded"
                    />
                    <span className="text-sm text-gray-700">{t('endWithCTA')}</span>
                  </label>
                  {includeLink && (
                    <p className="text-xs text-gray-400 mt-1 ml-6 italic">
                      {ctaText || websiteUrl}
                    </p>
                  )}
                </div>
              )}

              {/* Error */}
              {error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded text-sm text-red-700">{error}</div>}

              {/* Generate Button */}
              <button
                onClick={generateArticles}
                disabled={loading}
                className="w-full bg-[var(--ember-deep)] hover:bg-[var(--ink)] disabled:bg-gray-400 text-[var(--on-ember)] font-medium py-2 px-4 rounded-lg transition-colors"
              >
                {loading ? t('generating') : t('generate')}
              </button>
            </div>
          </div>

          {/* Results */}
          <div className="md:col-span-2">
            {loading && (
              <div className="bg-white rounded-lg border border-gray-200 p-8 text-center">
                <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                <p className="text-gray-600 mt-4">{t('generating2')}</p>
              </div>
            )}

            {!loading && articles.length > 0 && (
              <div className="space-y-6">
                <h2 className="text-lg font-semibold text-gray-900">{t('generatedTitle')}</h2>
                {articles.map((article) => (
                  <div key={article.id} className="bg-white rounded-lg border border-gray-200 p-6">
                    {/* Platform Badge */}
                    <div className="mb-4">
                      <span className="inline-block px-3 py-1 bg-[var(--ember-tint-bg)] text-[var(--ember-deep)] rounded-full text-sm font-medium capitalize">
                        {article.platform}
                      </span>
                    </div>

                    {/* Title */}
                    <h3 className="text-xl font-semibold text-gray-900 mb-2">{article.title}</h3>

                    {/* Content */}
                    {editingId === article.id ? (
                      <div className="mb-4">
                        <textarea
                          value={editDraft}
                          onChange={(e) => setEditDraft(e.target.value)}
                          rows={12}
                          className="w-full px-3 py-2 border border-blue-400 rounded-lg text-sm text-gray-800 focus:outline-none focus:ring-2 focus:ring-[var(--ember-deep)] resize-y"
                        />
                        <div className="flex gap-2 mt-2">
                          <button
                            onClick={() => saveEdit(article.id)}
                            disabled={saving}
                            className="px-4 py-1.5 bg-[var(--ember-deep)] hover:bg-[var(--ink)] disabled:bg-gray-400 text-[var(--on-ember)] text-sm font-medium rounded-lg transition-colors"
                          >
                            {saving ? t('saving') : t('saveEdit')}
                          </button>
                          <button
                            onClick={cancelEdit}
                            className="px-4 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 text-sm font-medium rounded-lg transition-colors"
                          >
                            {t('cancel')}
                          </button>
                        </div>
                      </div>
                    ) : (
                      <div className="bg-gray-50 rounded-lg p-4 mb-2 max-h-48 overflow-y-auto">
                        <div className="text-gray-700 whitespace-pre-wrap text-sm">
                          {renderMarkdown(article.content)}
                        </div>
                      </div>
                    )}

                    {/* Action buttons */}
                    {editingId !== article.id && (
                      <div className="flex gap-3 mb-4">
                        <button
                          onClick={() => startEdit(article)}
                          className="text-sm text-gray-600 hover:text-gray-800 font-medium"
                        >
                          {t('edit')}
                        </button>
                        <button
                          onClick={() => copyToClipboard(article.content)}
                          className="text-sm hover:underline font-medium"
                        >
                          {t('copy')}
                        </button>
                      </div>
                    )}

                    {/* Image */}
                    {article.image_url && (
                      <div className="mt-4">
                        <img
                          src={article.image_url}
                          alt={article.title}
                          className="w-full h-48 object-cover rounded-lg border border-gray-200"
                          onError={(e) => {
                            e.currentTarget.src = 'https://via.placeholder.com/300x200?text=Image+Not+Available'
                          }}
                        />
                      </div>
                    )}
                  </div>
                ))}

                {/* Navigation hint */}
                <div className="bg-[var(--ember-tint-bg)] border border-[var(--ember-tint-border)] rounded-lg p-4 flex items-start gap-3">
                  <span className="text-xl">💡</span>
                  <div>
                    <p className="text-sm font-medium text-blue-900">{t('backgroundGraphicsNote')}</p>
                    <p className="text-sm text-blue-700 mt-1">
                      {t('backgroundGraphicsDesc')}{' '}
                      <Link
                        href={`/dashboard/products/${productId}`}
                        className="underline font-medium hover:text-blue-900"
                      >
                        {t('backgroundGraphicsLink')}
                      </Link>
                      {' '}{t('backgroundGraphicsTime')}
                    </p>
                  </div>
                </div>
              </div>
            )}

            {!loading && articles.length === 0 && !error && (
              <div className="bg-white rounded-lg border border-gray-200 p-8 text-center">
                <p className="text-gray-500">{t('emptyPrompt')}</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
